name: Deploy Nginx Server

on:
  workflow_dispatch:  # Enable manual triggering of workflow

jobs:
  deploy:
    runs-on: EC2-instance

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: SHA256:STWeQzEodHInU3CCGUilJ3G+CFuHl6+ZMQ+VRQffK7Y

      - name: Install Nginx
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ <43.205.98.102> 'sudo yum update -y && sudo yum install nginx -y'

      - name: Start Nginx
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@<43.205.98.102> 'sudo systemctl start nginx'
 
      - name: Enable Nginx on boot
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@<43.205.98.102>'sudo systemctl enable nginx'

      - name: Verify Nginx Status
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@<YOUR_EC2_PUBLIC_IP> 'sudo systemctl status nginx'

